# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messagebox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 414)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/1486564410-chat_81504.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pushButton_MessageBox = QtWidgets.QPushButton(Form)
        self.pushButton_MessageBox.setGeometry(QtCore.QRect(180, 260, 181, 81))
        self.pushButton_MessageBox.setIcon(icon)
        self.pushButton_MessageBox.setObjectName("pushButton_MessageBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Message Box"))
        self.pushButton_MessageBox.setText(_translate("Form", "Message Box"))
import messagebox_rc
