# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doktor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DoktorEkrani(object):
    def setupUi(self, DoktorEkrani):
        DoktorEkrani.setObjectName("DoktorEkrani")
        DoktorEkrani.resize(510, 647)
        self.label = QtWidgets.QLabel(DoktorEkrani)
        self.label.setGeometry(QtCore.QRect(40, 10, 381, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_doktorbilgi = QtWidgets.QLabel(DoktorEkrani)
        self.label_doktorbilgi.setGeometry(QtCore.QRect(20, 100, 561, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_doktorbilgi.setFont(font)
        self.label_doktorbilgi.setObjectName("label_doktorbilgi")
        self.label_3 = QtWidgets.QLabel(DoktorEkrani)
        self.label_3.setGeometry(QtCore.QRect(130, 180, 381, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_doktormesaj = QtWidgets.QTextEdit(DoktorEkrani)
        self.textEdit_doktormesaj.setGeometry(QtCore.QRect(50, 260, 391, 191))
        self.textEdit_doktormesaj.setObjectName("textEdit_doktormesaj")
        self.pushButton_gonder = QtWidgets.QPushButton(DoktorEkrani)
        self.pushButton_gonder.setGeometry(QtCore.QRect(150, 490, 191, 101))
        self.pushButton_gonder.setObjectName("pushButton_gonder")

        self.retranslateUi(DoktorEkrani)
        QtCore.QMetaObject.connectSlotsByName(DoktorEkrani)

    def retranslateUi(self, DoktorEkrani):
        _translate = QtCore.QCoreApplication.translate
        DoktorEkrani.setWindowTitle(_translate("DoktorEkrani", "Doktor Ekranı"))
        self.label.setText(_translate("DoktorEkrani", "Randevulu Hastadan Mesaj"))
        self.label_doktorbilgi.setText(_translate("DoktorEkrani", "Duyuru: Şu an da hastadan bir\n"
"bilgi bulunmamaktadır."))
        self.label_3.setText(_translate("DoktorEkrani", "Doktor Mesaj Ekranı"))
        self.pushButton_gonder.setText(_translate("DoktorEkrani", "Hasta Ekranına Mesaj Gönder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DoktorEkrani = QtWidgets.QWidget()
    ui = Ui_DoktorEkrani()
    ui.setupUi(DoktorEkrani)
    DoktorEkrani.show()
    sys.exit(app.exec_())
