# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hasta.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HastaEkrani(object):
    def setupUi(self, HastaEkrani):
        HastaEkrani.setObjectName("HastaEkrani")
        HastaEkrani.resize(494, 648)
        self.label = QtWidgets.QLabel(HastaEkrani)
        self.label.setGeometry(QtCore.QRect(70, 10, 381, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_hastabilgi = QtWidgets.QLabel(HastaEkrani)
        self.label_hastabilgi.setGeometry(QtCore.QRect(40, 120, 561, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_hastabilgi.setFont(font)
        self.label_hastabilgi.setObjectName("label_hastabilgi")
        self.textEdit_hastamesaj = QtWidgets.QTextEdit(HastaEkrani)
        self.textEdit_hastamesaj.setGeometry(QtCore.QRect(50, 260, 391, 191))
        self.textEdit_hastamesaj.setObjectName("textEdit_hastamesaj")
        self.pushButton_gonder = QtWidgets.QPushButton(HastaEkrani)
        self.pushButton_gonder.setGeometry(QtCore.QRect(150, 490, 191, 101))
        self.pushButton_gonder.setObjectName("pushButton_gonder")

        self.retranslateUi(HastaEkrani)
        QtCore.QMetaObject.connectSlotsByName(HastaEkrani)

    def retranslateUi(self, HastaEkrani):
        _translate = QtCore.QCoreApplication.translate
        HastaEkrani.setWindowTitle(_translate("HastaEkrani", "Hasta Ekranı"))
        self.label.setText(_translate("HastaEkrani", "Randevulu Hasta Bilgi Mesajı"))
        self.label_hastabilgi.setText(_translate("HastaEkrani", "Duyuru: Şu an da doktordan bir\n"
"bilgi bulunmamaktadır."))
        self.pushButton_gonder.setText(_translate("HastaEkrani", "Doktora Mesaj Gönder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HastaEkrani = QtWidgets.QWidget()
    ui = Ui_HastaEkrani()
    ui.setupUi(HastaEkrani)
    HastaEkrani.show()
    sys.exit(app.exec_())
