# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secilenler.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(499, 376)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 241, 181))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_mayonez = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_mayonez.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.checkBox_mayonez.setObjectName("checkBox_mayonez")
        self.checkBox_ketcap = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_ketcap.setGeometry(QtCore.QRect(20, 70, 81, 20))
        self.checkBox_ketcap.setObjectName("checkBox_ketcap")
        self.checkBox_acisos = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_acisos.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.checkBox_acisos.setObjectName("checkBox_acisos")
        self.pushButton_Goster = QtWidgets.QPushButton(Form)
        self.pushButton_Goster.setGeometry(QtCore.QRect(110, 250, 93, 28))
        self.pushButton_Goster.setObjectName("pushButton_Goster")
        self.label_soslar = QtWidgets.QLabel(Form)
        self.label_soslar.setGeometry(QtCore.QRect(60, 320, 411, 31))
        self.label_soslar.setObjectName("label_soslar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Soslar"))
        self.checkBox_mayonez.setText(_translate("Form", "Mayonez"))
        self.checkBox_ketcap.setText(_translate("Form", "Ketçap"))
        self.checkBox_acisos.setText(_translate("Form", "Acı Sos"))
        self.pushButton_Goster.setText(_translate("Form", "Göster"))
        self.label_soslar.setText(_translate("Form", "Seçilenler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
