# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablewidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1083, 609)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 130, 551, 431))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(670, 120, 291, 421))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(0, 30, 291, 341))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_SatirEkle = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/arti/Plus_36851.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SatirEkle.setIcon(icon)
        self.pushButton_SatirEkle.setObjectName("pushButton_SatirEkle")
        self.verticalLayout.addWidget(self.pushButton_SatirEkle)
        self.pushButton_SatirSil = QtWidgets.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/eksi/Minus_36877.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SatirSil.setIcon(icon1)
        self.pushButton_SatirSil.setObjectName("pushButton_SatirSil")
        self.verticalLayout.addWidget(self.pushButton_SatirSil)
        self.pushButton_SutunEkle = QtWidgets.QPushButton(self.widget)
        self.pushButton_SutunEkle.setIcon(icon)
        self.pushButton_SutunEkle.setObjectName("pushButton_SutunEkle")
        self.verticalLayout.addWidget(self.pushButton_SutunEkle)
        self.pushButton_SutunSil = QtWidgets.QPushButton(self.widget)
        self.pushButton_SutunSil.setIcon(icon1)
        self.pushButton_SutunSil.setObjectName("pushButton_SutunSil")
        self.verticalLayout.addWidget(self.pushButton_SutunSil)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 10, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Soyad"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Tel"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.pushButton_SatirEkle.setText(_translate("Form", "Satır Ekle"))
        self.pushButton_SatirSil.setText(_translate("Form", "Satır Sil"))
        self.pushButton_SutunEkle.setText(_translate("Form", "Sütun Ekle"))
        self.pushButton_SutunSil.setText(_translate("Form", "Sütun Sil"))
        self.label.setText(_translate("Form", "Kişi Kayıtları"))
import ikonlar_rc
